#!/usr/bin/env python3
"""
generate_table3.py
------------------
Auto-generate LaTeX Table 3 (results table) from checkpoint meta.json files.

Usage:
    python scripts/generate_table3.py --ckpt_dir /content/drive/MyDrive/grokking_research_v3/checkpoints
    python scripts/generate_table3.py --ckpt_dir checkpoints  # local run

Output:
    Prints the complete LaTeX table3 source to stdout.
    Also saves to paper/table3_autogen.tex if --save flag is set.
"""
import argparse
import json
import math
import os
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from src.datasets import (
    COMPLEXITY_MEASURES,
    get_complexity_score,
    get_complexity_score_v2,
)

# Mapping from op_symbol to display label (LaTeX-safe for .tex output)
# NOTE: \bmod is valid in LaTeX documents (requires amsmath). These strings are
# written to paper/table3_autogen.tex — NOT rendered by matplotlib, so \bmod is correct here.
OP_LABELS = {
    "add":      r"$(a+b)\bmod 113$",
    "sub":      r"$(a-b)\bmod 113$",
    "mul":      r"$(a\times b)\bmod 113$",
    "ring_add": r"$(a+b)\bmod 100$",
    "s3":       r"$S_3$ ($|G|=6$)",
    "d5":       r"$D_5$ ($|G|=10$)",
    "a4":       r"$A_4$ ($|G|=12$)",
    "s4":       r"$S_4$ ($|G|=24$)",
}

# Expected p-values for each op (used to find meta files)
OP_P = {
    "add":      113,
    "sub":      113,
    "mul":      113,
    "ring_add": 100,
    "s3":       6,
    "d5":       10,
    "a4":       12,
    "s4":       24,
}

SEEDS = [42, 1, 7]

def load_meta(op: str, p: int, seed: int, ckpt_dir: Path) -> dict:
    """Load a single meta.json file; return empty dict if not found."""
    path = ckpt_dir / f"{op}_p{p}_seed{seed}_meta.json"
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)

def load_agg(op: str, p: int, ckpt_dir: Path) -> dict:
    """Load the multi-seed aggregate JSON if available."""
    path = ckpt_dir / f"{op}_p{p}_multi_seed_agg.json"
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)

def bootstrap_ci(values: list, n_boot: int = 2000, seed: int = 0) -> tuple:
    """Return (mean, lo95, hi95) via bootstrap."""
    import numpy as np
    if not values:
        return (None, None, None)
    arr = [v for v in values if v is not None]
    if not arr:
        return (None, None, None)
    rng  = np.random.default_rng(seed)
    arr  = [float(v) for v in arr]
    pt   = float(sum(arr) / len(arr))
    boot = [float(sum(rng.choice(arr, size=len(arr), replace=True)) / len(arr))
            for _ in range(n_boot)]
    lo   = float(sorted(boot)[int(0.025 * n_boot)])
    hi   = float(sorted(boot)[int(0.975 * n_boot)])
    return pt, lo, hi

def fmt_epoch(mean, lo, hi) -> str:
    """Format grokking epoch as 'mean (lo--hi)'."""
    if mean is None:
        return r"\textit{N/A}"
    if lo is None or hi is None:
        return f"{int(mean)}"
    return f"{int(mean)} ({int(lo)}--{int(hi)})"

def fmt_float(v, digits=2) -> str:
    if v is None:
        return "—"
    return f"{v:.{digits}f}"

def get_table_row(op: str, ckpt_dir: Path) -> dict:
    """Collect all data for one table row."""
    p    = OP_P[op]
    agg  = load_agg(op, p, ckpt_dir)
    metas = [load_meta(op, p, s, ckpt_dir) for s in SEEDS]

    # Grokking epoch
    grok_epochs = [m.get("final_grok_epoch") or m.get("grok_epoch")
                   for m in metas if m]
    grok_epochs = [e for e in grok_epochs if e is not None]
    if agg.get("all_grok_epochs"):
        grok_epochs = agg["all_grok_epochs"]
    mean_ge, lo_ge, hi_ge = bootstrap_ci(grok_epochs)

    # Final test accuracy
    test_accs = [m.get("final_test_acc") for m in metas if m]
    test_accs = [a for a in test_accs if a is not None]
    mean_ta, _, _ = bootstrap_ci(test_accs)

    # Complexity scores
    c1 = get_complexity_score(op)
    c2 = get_complexity_score_v2(op)

    # Irrep info from COMPLEXITY_MEASURES
    cm  = COMPLEXITY_MEASURES[op]
    max_d = cm["max_irrep_dim"]
    n_ir  = cm["n_irreps"]

    return {
        "op":           op,
        "label":        OP_LABELS[op],
        "grok_mean":    mean_ge,
        "grok_lo":      lo_ge,
        "grok_hi":      hi_ge,
        "grok_n":       len(grok_epochs),
        "test_acc":     mean_ta,
        "max_irrep_dim":max_d,
        "n_irreps":     n_ir,
        "complexity_v1":c1,
        "complexity_v2":c2,
        "is_abelian":   cm["is_abelian"],
    }

def generate_latex_table(rows: list) -> str:
    lines = []
    lines.append(r"""% ─── Table 3: Experimental Results (auto-generated by scripts/generate_table3.py)
% Regenerate with: python scripts/generate_table3.py --ckpt_dir <path>
\begin{table}[t]
  \centering
  \small
  \caption{%
    Experimental results across all eight algebraic tasks.
    Grokking epoch is the mean (95\% bootstrap CI) across seeds.
    $C_1(G)$ = ad-hoc complexity score (Eq.~\ref{eq:complexity_v1});
    $C_2(G)$ = theory-grounded score (Eq.~\ref{eq:complexity_v2}).
    N/A = experiment did not grok within the epoch budget.
  }
  \label{tab:results}
  \setlength{\tabcolsep}{4pt}
  \begin{tabular}{lcccccc}
    \toprule
    Operation & Structure & Grok Epoch (95\% CI) & Test Acc & $d_{\max}$ & $C_1(G)$ & $C_2(G)$ \\
    \midrule""")

    for r in rows:
        structure = "Abelian" if r["is_abelian"] else "Non-abelian"
        grok_str  = fmt_epoch(r["grok_mean"], r["grok_lo"], r["grok_hi"])
        acc_str   = fmt_float(r["test_acc"], 3) if r["test_acc"] else "—"
        lines.append(
            f"    {r['label']} & {structure} & {grok_str} & "
            f"{acc_str} & {r['max_irrep_dim']} & "
            f"{fmt_float(r['complexity_v1'], 1)} & {fmt_float(r['complexity_v2'], 2)} \\\\"
        )

    lines.append(r"""    \bottomrule
  \end{tabular}
\end{table}""")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX Table 3 from experiment checkpoints."
    )
    parser.add_argument("--ckpt_dir", default="checkpoints",
                        help="Directory containing meta.json checkpoint files")
    parser.add_argument("--save", action="store_true",
                        help="Save output to paper/table3_autogen.tex")
    args = parser.parse_args()

    ckpt_dir = Path(args.ckpt_dir)
    if not ckpt_dir.exists():
        print(f"⚠️  Checkpoint directory not found: {ckpt_dir}")
        print("   No experiment data available — generating skeleton table with N/A values.")

    ops = ["add", "sub", "mul", "ring_add", "s3", "d5", "a4", "s4"]
    rows = [get_table_row(op, ckpt_dir) for op in ops]

    # Print data summary
    found = [r for r in rows if r["grok_mean"] is not None]
    print(f"\n📊  Table 3 generator: {len(found)}/{len(ops)} ops have grokking data")
    for r in rows:
        ge = f"{int(r['grok_mean']):5d}" if r["grok_mean"] else "  N/A"
        ta = f"{r['test_acc']:.3f}" if r["test_acc"] else "  —  "
        print(f"   {r['op']:10s}  grok_epoch={ge}  test_acc={ta}  "
              f"C1={r['complexity_v1']:.1f}  C2={r['complexity_v2']:.2f}")

    latex = generate_latex_table(rows)
    print("\n" + "─" * 70)
    print(latex)
    print("─" * 70)

    if args.save:
        out = _ROOT / "paper" / "table3_autogen.tex"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(latex)
        print(f"\n✅  Saved → {out}")

if __name__ == "__main__":
    main()
